// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: message-queueing.proto

package queueing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueueServiceClient is the client API for QueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueServiceClient interface {
	SubmitMessages(ctx context.Context, in *SubmitMessagesRequest, opts ...grpc.CallOption) (*SubmitMessagesResponse, error)
	RetrieveMessages(ctx context.Context, in *RetrieveMessagesRequest, opts ...grpc.CallOption) (*RetrieveMessagesResponse, error)
	AcknowledgeMessages(ctx context.Context, in *AcknowledgeMessagesRequest, opts ...grpc.CallOption) (*AcknowledgeMessagesResponse, error)
}

type queueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueServiceClient(cc grpc.ClientConnInterface) QueueServiceClient {
	return &queueServiceClient{cc}
}

func (c *queueServiceClient) SubmitMessages(ctx context.Context, in *SubmitMessagesRequest, opts ...grpc.CallOption) (*SubmitMessagesResponse, error) {
	out := new(SubmitMessagesResponse)
	err := c.cc.Invoke(ctx, "/message_queueing.QueueService/SubmitMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) RetrieveMessages(ctx context.Context, in *RetrieveMessagesRequest, opts ...grpc.CallOption) (*RetrieveMessagesResponse, error) {
	out := new(RetrieveMessagesResponse)
	err := c.cc.Invoke(ctx, "/message_queueing.QueueService/RetrieveMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) AcknowledgeMessages(ctx context.Context, in *AcknowledgeMessagesRequest, opts ...grpc.CallOption) (*AcknowledgeMessagesResponse, error) {
	out := new(AcknowledgeMessagesResponse)
	err := c.cc.Invoke(ctx, "/message_queueing.QueueService/AcknowledgeMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServiceServer is the server API for QueueService service.
// All implementations must embed UnimplementedQueueServiceServer
// for forward compatibility
type QueueServiceServer interface {
	SubmitMessages(context.Context, *SubmitMessagesRequest) (*SubmitMessagesResponse, error)
	RetrieveMessages(context.Context, *RetrieveMessagesRequest) (*RetrieveMessagesResponse, error)
	AcknowledgeMessages(context.Context, *AcknowledgeMessagesRequest) (*AcknowledgeMessagesResponse, error)
	mustEmbedUnimplementedQueueServiceServer()
}

// UnimplementedQueueServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQueueServiceServer struct {
}

func (UnimplementedQueueServiceServer) SubmitMessages(context.Context, *SubmitMessagesRequest) (*SubmitMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMessages not implemented")
}
func (UnimplementedQueueServiceServer) RetrieveMessages(context.Context, *RetrieveMessagesRequest) (*RetrieveMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveMessages not implemented")
}
func (UnimplementedQueueServiceServer) AcknowledgeMessages(context.Context, *AcknowledgeMessagesRequest) (*AcknowledgeMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessages not implemented")
}
func (UnimplementedQueueServiceServer) mustEmbedUnimplementedQueueServiceServer() {}

// UnsafeQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServiceServer will
// result in compilation errors.
type UnsafeQueueServiceServer interface {
	mustEmbedUnimplementedQueueServiceServer()
}

func RegisterQueueServiceServer(s grpc.ServiceRegistrar, srv QueueServiceServer) {
	s.RegisterService(&QueueService_ServiceDesc, srv)
}

func _QueueService_SubmitMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).SubmitMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message_queueing.QueueService/SubmitMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).SubmitMessages(ctx, req.(*SubmitMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_RetrieveMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).RetrieveMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message_queueing.QueueService/RetrieveMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).RetrieveMessages(ctx, req.(*RetrieveMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_AcknowledgeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).AcknowledgeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message_queueing.QueueService/AcknowledgeMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).AcknowledgeMessages(ctx, req.(*AcknowledgeMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueService_ServiceDesc is the grpc.ServiceDesc for QueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_queueing.QueueService",
	HandlerType: (*QueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMessages",
			Handler:    _QueueService_SubmitMessages_Handler,
		},
		{
			MethodName: "RetrieveMessages",
			Handler:    _QueueService_RetrieveMessages_Handler,
		},
		{
			MethodName: "AcknowledgeMessages",
			Handler:    _QueueService_AcknowledgeMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message-queueing.proto",
}
